### PR TITLE
Fixed `ModuleNotFoundError: No module named 'win32com'`

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by vidhanio** [comment]
Weird, I've never experienced this. What requires this?

**Comment by ghost** [comment]
> Weird, I've never experienced this. What requires this?

Module that got me in error while running installation of modules. Maybe you had this moduel.

**Comment by vidhanio** [comment]
what are your system specifications? The program should definitely work without this, I have reinstalled this in virtual environments multiple times without the error.

**Comment by ghost** [comment]
> what are your system specifications? The program should definitely work without this, I have reinstalled this in virtual environments multiple times without the error.

At that time I was on windows, 8gb ram, 1g
Tb hhd,4core cpu

**Comment by vidhanio** [comment]
pywin32 doesn't have cross-platform support, I would need more information. This ran fine on my machine on windows for as long as I was developing it.

**Pull request merged**
